"""Add v2.0 SentPost columns

Revision ID: 007
Revises: 006
Create Date: 2024-05-24 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '007'
down_revision: Union[str, None] = '006'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sent_posts', sa.Column('author', sa.String(length=256), nullable=True))
    op.add_column('sent_posts', sa.Column('media_url', sa.String(length=1024), nullable=True))
    op.add_column('sent_posts', sa.Column('media_type', sa.String(length=32), nullable=True))
    op.add_column('sent_posts', sa.Column('thumbnail_url', sa.String(length=1024), nullable=True))
    op.add_column('sent_posts', sa.Column('duration', sa.String(length=16), nullable=True))
    op.add_column('sent_posts', sa.Column('stats_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sent_posts', 'stats_json')
    op.drop_column('sent_posts', 'duration')
    op.drop_column('sent_posts', 'thumbnail_url')
    op.drop_column('sent_posts', 'media_type')
    op.drop_column('sent_posts', 'media_url')
    op.drop_column('sent_posts', 'author')
    # ### end Alembic commands ###
